version: '3.8'

services:
  # MCP Hub Central - Orchestrateur
  mcp-hub:
    build:
      context: ./mcp-hub
      dockerfile: Dockerfile
    ports:
      - "4000:4000"  # MCP Hub API
      - "4001:4001"  # MCP Server Protocol
    environment:
      - MCP_HUB_PORT=4000
      - MCP_SERVER_PORT=4001
      - OLLAMA_HOST=host.docker.internal:11434
      - PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY}
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
    volumes:
      - ./data:/app/data
      - ./mcp-hub:/app:cached
    restart: unless-stopped
    networks:
      - mcp-network

  # Frontend MCP-aware  
  mcp-frontend:
    build:
      context: ./frontend-simple
      dockerfile: Dockerfile
    ports:
      - "4002:4002"
    restart: unless-stopped
    networks:
      - mcp-network
    depends_on:
      - mcp-hub

  # Ollama MCP Proxy (pour standardiser l'interface)
  ollama-mcp:
    build:
      context: ./mcp-servers/ollama
      dockerfile: Dockerfile
    ports:
      - "4003:4003"
    environment:
      - OLLAMA_HOST=host.docker.internal:11434
      - MCP_PORT=4003
    restart: unless-stopped
    networks:
      - mcp-network

  # Perplexity MCP Server
  perplexity-mcp:
    build:
      context: ./mcp-servers/perplexity
      dockerfile: Dockerfile
    ports:
      - "4004:4004"
    environment:
      - PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY}
      - MCP_PORT=4004
    restart: unless-stopped
    networks:
      - mcp-network

  # Memory/Context MCP Server
  memory-mcp:
    build:
      context: ./mcp-servers/memory
      dockerfile: Dockerfile
    ports:
      - "4005:4005"
    environment:
      - MCP_PORT=4005
      - DATABASE_URL=sqlite:///app/data/memory.db
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    networks:
      - mcp-network

  # Tools MCP Server (file ops, web, etc.)
  tools-mcp:
    build:
      context: ./mcp-servers/tools
      dockerfile: Dockerfile
    ports:
      - "4006:4006"
    environment:
      - MCP_PORT=4006
    volumes:
      - ./workspace:/app/workspace
      - ./data:/app/data
    restart: unless-stopped
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge

volumes:
  mcp_data: